name: mobile_umed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: 3.32.5

dependencies:
  flutter:
    sdk: flutter

  # Translation
  flutter_localizations:
    sdk: flutter

  # Navigation
  go_router: ^16.0.0

  #State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #Maps
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  latlong2: ^0.9.1
  flutter_map_cache: ^2.0.0
  
  # Location GPS 
  geolocator: ^14.0.2  
  flutter_map_location_marker: ^10.1.0 

  #Models
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0 

  #HTTP Client
  dio: ^5.8.0+1

  # Redirects
  url_launcher: ^6.2.3

  #Widgets
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0 

  #Code Generation
  build_runner: ^2.5.4

  # Loading animations
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.20.2
  fast_immutable_collections: ^11.0.4

  # Caching
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # env
  envied: ^1.1.1

  # others
  flutter_foreground_task: ^9.1.0
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  solvro_config: ^1.0.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  flutter_lints: ^6.0.0
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/app/assets/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
      
lint_staged:
  "lib/**.dart": dart format && dart fix --apply
