name: mobile_umed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.8.1

  #State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #Maps
  flutter_map: ^8.1.1

  #Models
  freezed: ^3.0.6

  #HTTP Client
  dio: ^5.8.0+1

  #Widgets
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17 

  #Code Generation
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  solvro_config: ^1.0.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/app/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    
lint_staged:
  "lib/**.dart": dart format && dart fix --apply
